import type { Metadata } from "next";
import localFont from "next/font/local";

import Providers from "./Providers";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Next App With Single-spa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <script type="systemjs-importmap">
          {
            JSON.stringify({
              imports: {
                "react": "https://cdn.jsdelivr.net/npm/react@16.13.1/umd/react.production.min.js",
                "react-dom": "https://cdn.jsdelivr.net/npm/react-dom@16.13.1/umd/react-dom.production.min.js",
                "@isomorphic-mf/navbar": "https://storage.googleapis.com/isomorphic.microfrontends.app/navbar/179aaa63f3f220b6d0c4675865d16d3b4ddd8995/isomorphic-mf-navbar.js",
                "@isomorphic-mf/navbar/": "https://storage.googleapis.com/isomorphic.microfrontends.app/navbar/179aaa63f3f220b6d0c4675865d16d3b4ddd8995/",
                "@isomorphic-mf/root-config": "https://storage.googleapis.com/isomorphic.microfrontends.app/root-config/016db7599625c5e00526f64850e0c845201d0f81/isomorphic-mf-root-config.js",
                "@isomorphic-mf/root-config/": "https://storage.googleapis.com/isomorphic.microfrontends.app/root-config/016db7599625c5e00526f64850e0c845201d0f81/",
                "single-spa": "https://cdn.jsdelivr.net/npm/single-spa@5.5.3/lib/system/single-spa.min.js",
                "@isomorphic-mf/pokemons": "https://storage.googleapis.com/isomorphic.microfrontends.app/pokemons/8bd859cb4ca90b34f577c701aeaa1dcdada3a164/isomorphic-mf-pokemons.js",
                "@isomorphic-mf/pokemons/": "https://storage.googleapis.com/isomorphic.microfrontends.app/pokemons/8bd859cb4ca90b34f577c701aeaa1dcdada3a164/"
              }
            })
          }
          </script>
          <script src="https://cdn.jsdelivr.net/npm/systemjs/dist/system.min.js"></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
